import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { getDictionary, Locale } from "@/app/get-dictionary";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Consultimer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, 
  params,
}: { 
  children: React.ReactNode, 
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const currentLang = lang as Locale;
  const dictionary = await getDictionary(currentLang);
  return (
    <html lang={lang}>
      <body className="pt-20">
        <Navbar dict={dictionary.navbar} /> 
        {children}
        <Footer dict={dictionary.footer} />
      </body>
    </html>
  );
}
